displayName: Version
description: Routes to access data about a pub's versions
get: 
  description: Get pub data. Includes connected user, discussion, label, etc data. If the user's cookie or token is included, private data (private discussions, versions, etc) are included.
  queryParameters:
    pubId:
      type: string
      required: true
    versionId:
      type: string
      required: true
  responses:
    200:
      body:
        application/json:
          example: |
            {
                id: 9,
            }
    500:
      body:
        application/json:
          example: "Pub not found"
post:
  description: Create a new version. New files are added through this interface
  body:
    application/json:
      formParameters:
        pubId: 
          description: id of the Pub this version will be attached to
          required: true
        versionMessage: 
          description: message for this given version
          required: true
        isPublished:
          description: Boolean for whether this version should be published
          required: true
        files: 
          description: All files, those that are new should NOT include an "id" field and they will be added.
        defaultFile:
          description: Default file for this version
        newFileAttribution: 
          description: |
            Array of objects with {source: [file.name], destination: [file.name]}. 
        newFileRelations: 
          description: |
            Array of objects with {fileName: [file.name], userId: [user's id]}. 

  responses:
    200:
      body:
        application/json:
          example: |
            {
                "id": 15,
            }
    500:
      body:
        application/json:
          example: |
            {
              error : "Error creating pub"
            }
put:
  description: |
    Set the isPublished value of a version to TRUE
  body:
    application/json:
      formParameters:
        pubId: 
          description: id of the pub to be changed
          required: true
        versionId: 
          description: id of the version to be changed
          required: true
        doi: 
          description: new DOI for a given version
        defaultFile: 
          description: new defautlFile for a given version
  responses:
    200:
      body:
        application/json:
          example: true
    500:
      body:
        application/json:
          example: |
            {
              error : "Error updating pub"
            }
delete:
  description: Delete the pub
  body:
    application/json:
      formParameters:
        pubId: 
          description: id of the pub to be deleted
  responses:
    200:
      body:
        application/json:
          example: "Pub set inactive"
    500:
      body:
        application/json:
          example: |
            {
              error : "Error deleting pub"
            }