#%RAML 0.8
title: PubPub API
documentation:
  - title: Introduction
    content: |
      This API provides full access to the PubPub database.
      All requests and responses are in the form of application/json.
      Requests should be made to the following URL paths added to the hostname
      https://api.pubpub.org. For example https://api.pubpub.org/user/travis.
  - title: Authentication
    content: |
      Access to secured URLs is granted by included an apiToken in the body of POST, PUT, and DELETE requests or an apiToken in the query of GET requests. The apiToken can be found on the settings page of each users profile (https://wwww.pubpub.org/user/travis/settings). 
  - title: Contributing
    content: |
      This API documentation and the associated server code is all open source: https://github.com/pubpub/pubpub-api. Contributions, fixes, bug reports are welcome!

version: v2
protocols: [ HTTPS ]
baseUri: https://api.pubpub.org
mediaType: application/json

/user: !include routes/user/user.raml
/signup: !include routes/signUp/signUp.raml
/login: !include routes/login/login.raml
/logout: !include routes/logout/logout.raml
