displayName: Reaction
description: Routes to access data about a the reactions associated with a pub
get: 
  description: Get pub data. Includes connected user, discussion, label, etc data. If the user's cookie or token is included, private data (private discussions, versions, etc) are included.
  queryParameters:
    pubId:
      type: string
      required: true
  responses:
    200:
      body:
        application/json:
          example: |
            {
                id: 9,
            }
    500:
      body:
        application/json:
          example: "Pub not found"
post:
  description: Create a new User
  body:
    application/json:
      formParameters:
        pubId: 
          description: id of the pub this reaction is being added to
          required: true
        reactionId: 
          description: id of the reaction to be added
          required: true
  responses:
    200:
      body:
        application/json:
          example: |
            {
                "id": 15,
            }
    500:
      body:
        application/json:
          example: |
            {
              error : "Error creating pub"
            }
delete:
  description: Delete the pub
  body:
    application/json:
      formParameters:
        pubId: 
          description: id of the pub this reaction is being removed from
          required: true
        reactionId: 
          description: id of the reaction to be removed
          required: true
  responses:
    200:
      body:
        application/json:
          example: "Pub set inactive"
    500:
      body:
        application/json:
          example: |
            {
              error : "Error deleting pub"
            }