displayName: Journal
description: Routes to access data about Journals
get:
  queryParameters:
    slug:
      type: string
      required: true
  responses:
    200:
      body:
        application/json:
          example: true
post:
  description: Create a new Journal
  body:
    application/json:
      formParameters:
        title: 
          description: title used for the new journal
          required: true
        slug: 
          description: slug used for the journal url
          required: true
        short description: 
          description: short description used for the new journal
          required: true
        about:
          description: long description to be used for the new journal
        logo:
          description: Large log for the new journal. Can be used in the header of the journal's page
        avatar:
          description: square avatar for the new journal. Used on preview cards
        website:
          description: website url
        twitter:
          description: twitter account
        facebook:
          description: facebook account
  responses:
    200:
      body:
        application/json:
          example: |
            {
                "id": 15,
                "slug": "my-journal",
                "title": "My Journal",
            }
    500:
      body:
        application/json:
          example: |
            {
              error : "Error creating journal"
            }
put:
  description: |
    Used to allow a journal admin to update the journal. 
  body:
    application/json:
      formParameters:
        journalId: 
          description: id of the journal to be changed
          required: true
        slug: 
          description: new slug 
        title:
          description: new title
        description: 
          description: new description
        about: 
          description: new about
        logo: 
          description: new logo
        avatar: 
          description: new avatar
        website: 
          description: new website
        twitter: 
          description: new twitter
        facebook: 
          description: new facebook
        headerColor: 
          description: new headerColor
        headerMode: 
          description: new headerMode
        headerAlign: 
          description: new headerAlign
        headerImage: 
          description: new headerImage
  responses:
    200:
      body:
        application/json:
          example: true
    500:
      body:
        application/json:
          example: |
            {
              error : "Error updating journal"
            }
delete:
  description: Delete the journal
  body:
    application/json:
      formParameters:
        journal: 
          description: id of the journal to be deleted
  responses:
    200:
      body:
        application/json:
          example: "Journal set inactive"
    500:
      body:
        application/json:
          example: |
            {
              error : "Error deleting journal"
            }
/admins: !include ../journalAdmins/journalAdmins.raml
/submits: !include ../journalSubmits/journalSubmits.raml
/features: !include ../journalFeatures/journalFeatures.raml
/labels: !include ../journalLabels/journalLabels.raml