displayName: Reset Password
description: Used to reset a users password
post:
  description: Reset a users password.
  body:
    application/json:
      formParameters:
        email:
          description: email of the account to login
          required: true
        password:
          description: password after hashing
          required: true
        hash:
          description: The reset password hash you were granted by PubPub.
          required: true
  responses:
    200:
      body:
        application/json:
          example: |
            {
            }
    401:
      body:
        application/json:
          example: "Unauthorized"

/reset: !include ../userPasswordReset/userPasswordReset.raml
