displayName: Feature
description: Routes to access data about a pub's journal features
put:
  description: Change the isDisplayed value of a pubFeature
  body:
    application/json:
      formParameters:
        pubId: 
          description: id of the pub
          required: true
        journalId: 
          description: id of the journal
          required: true
        isDisplayed:
          description: BOOLEAN dictating whether the journal is featured on the front of the pub
  responses:
    200:
      body:
        application/json:
          example: |
            {
                "id": 15,
            }
    500:
      body:
        application/json:
          example: |
            {
              error : "Error creating pub"
            }