displayName: Reaction
description: Routes to access data about a the reactions associated with a pub
post:
  description: Create a new User
  body:
    application/json:
      formParameters:
        pubId: 
          description: id of the pub this reaction is being added to
          required: true
        replyRootPubId: 
          description: id of the pub containing the discussionn this reaction is being added to
          required: true
        reactionId: 
          description: id of the reaction to be added
          required: true

  responses:
    200:
      body:
        application/json:
          example: |
            {
                "id": 15,
            }
    500:
      body:
        application/json:
          example: |
            {
              error : "Error creating pub"
            }
delete:
  description: Delete the pub
  body:
    application/json:
      formParameters:
        pubId: 
          description: id of the pub this reaction is being removed from
          required: true
        replyRootPubId: 
          description: id of the pub containing the discussionn this reaction is removed from
          required: true
        reactionId: 
          description: id of the reaction to be removed
          required: true
  responses:
    200:
      body:
        application/json:
          example: "Pub set inactive"
    500:
      body:
        application/json:
          example: |
            {
              error : "Error deleting pub"
            }