displayName: Reviewer
description: Routes to access data about a pub's reviewers
post:
  description: Invite a new reviewer. Either email and name, or invitedUserId must be included. 
  body:
    application/json:
      formParameters:
        email: 
          description: email of the invited reviewer
        name: 
          description: name of the invited reviewer
          required: true
        pubId:
          description: id of the pub this reviewer is being invited to
          required: true
        invitedUserId:
          description: id of the invited user
        inviterUserId:
          description: id of the user who created the invitation
        inviterJouranlId:
          description: id of the journal the invitation is on behalf of

  responses:
    200:
      body:
        application/json:
          example: |
            {
                "id": 15,
            }
    500:
      body:
        application/json:
          example: |
            {
              error : "Error creating pub"
            }
put:
  description: |
    Used to allow a pub editor to update the pub. 
    Things like 'distinguishedClone' or fields that are applied by outside users have their own 
  body:
    application/json:
      formParameters:
        pubId: 
          description: id of the pub the invitation is connected to
          required: true
        invitationAccepted: 
          description: BOOLEAN
        invitationRejected: 
          description: BOOLEAN 
        rejectionReason:
          description: Reason for rejecting the review invitation
        
  responses:
    200:
      body:
        application/json:
          example: true
    500:
      body:
        application/json:
          example: |
            {
              error : "Error updating pub"
            }
