displayName: Pub
description: Routes to access data about Pubs
get: 
  description: Get pub data. Includes connected user, discussion, label, etc data. If the user's cookie or token is included, private data (private discussions, versions, etc) are included.
  queryParameters:
    slug:
      type: string
      required: true
  responses:
    200:
      body:
        application/json:
          example: |
            {
              id: 102,
              slug: "my-doc-url",
              title: "Analysis of Spectral Filters",
              description: "This document compares 45 spectral filters.",
              previewImage: "https://assets.pubpub.org/_testing/1483555461063.jpg",
              isClosed: null,
              hideAuthorsList: null,
              customAuthorList: null,
              distinguishedClone: null,
              inactive: null,
              isPublished: true,
              threadNumber: null,
              createdAt: "2017-01-04T18:44:23.506Z",
              updatedAt: "2017-01-06T15:53:34.908Z",
              replyRootPubId: null,
              replyParentPubId: null,
              licenseId: null,
              defaultContext: null,
              cloneParentPubId: null,
              contributors: [...],
              followers: [...],
              versions: [...],
              labels: [...],
              pubLabels: [...],
              pubSubmits: [...],
              clones: [...],
              invitedReviewers: [...],
              license: null,
              cloneParent: null,
              pubFeatures: [...],
              discussions: [...],
              canEdit: false,
              allReactions: [...]
            }
    500:
      body:
        application/json:
          example: "Pub not found"
post:
  description: Create a new Pub
  body:
    application/json:
      formParameters:
        slug: 
          description: slug used for the pub url
          required: true
        title: 
          description: title used for the new pub
          required: true
        previewImage:
          description: preview image to be used for the new pub
          required: true
        description:
          description: description of the new pub
  responses:
    200:
      body:
        application/json:
          example: |
            {
              id: 102,
              slug: "my-doc-url",
              title: "Analysis of Spectral Filters",
              description: "This document compares 45 popular spectral filters and measures their efficacy.",
              previewImage: "https://assets.pubpub.org/_testing/1483555461063.jpg",
              isClosed: null,
              hideAuthorsList: null,
              customAuthorList: null,
              distinguishedClone: null,
              inactive: null,
              isPublished: null,
              threadNumber: null,
              createdAt: "2017-01-06T13:20:05.290Z",
              updatedAt: "2017-01-06T13:20:05.290Z",
              replyRootPubId: null,
              replyParentPubId: null,
              licenseId: null,
              defaultContext: null,
              cloneParentPubId: null,
              contributors: [...],
              followers: [...]
            }
    500:
      body:
        application/json:
          example: |
            {
              error : "Error creating pub"
            }
put:
  description: |
    Used to allow a pub editor to update the pub. 
    Things like 'distinguishedClone' or fields that are applied by outside users have their own 
  body:
    application/json:
      formParameters:
        pubId: 
          description: id of the pub to be changed
          required: true
        slug: 
          description: new slug 
        title:
          description: new title
        description:
          description: new description
        previewImage:
          description: new image
        isClosed: 
          description: new isClosed state
        hideAuthors: 
          description: new hideAuthors state
        customAuthorList: 
          description: new customAuthorList
        licenseId: 
          description: new License state
        defaultContext:
            description: new id of the default context journal
        
  responses:
    200:
      body:
        application/json:
          example: true
    500:
      body:
        application/json:
          example: |
            {
              error : "Error updating pub"
            }
delete:
  description: Delete the pub
  body:
    application/json:
      formParameters:
        pubId: 
          description: id of the pub to be deleted
  responses:
    200:
      body:
        application/json:
          example: "Pub set inactive"
    500:
      body:
        application/json:
          example: |
            {
              error : "Error deleting pub"
            }

/file/relations: !include ../pubFileRelations/pubFileRelations.raml
/file/attributions: !include ../pubFileAttributions/pubFileAttributions.raml
/versions: !include ../pubVersions/pubVersions.raml
/contributors: !include ../pubContributors/pubContributors.raml
/contributor/roles: !include ../pubContributorRoles/pubContributorRoles.raml
/discussions: !include ../pubDiscussions/pubDiscussions.raml
/reviewers: !include ../pubReviewers/pubReviewers.raml
/labels: !include ../pubLabels/pubLabels.raml
/reactions: !include ../pubReactions/pubReactions.raml
/submits: !include ../pubSubmits/pubSubmits.raml
/features: !include ../pubFeatures/pubFeatures.raml



