displayName: Contributor
description: Routes to access data about a pub's contributors
post:
  description: Create a new User
  body:
    application/json:
      formParameters:
        userId: 
          description: id of the user to be added
          required: true
        pubId: 
          description: id of the pub this contributor is being added to
          required: true
  responses:
    200:
      body:
        application/json:
          example: |
            {
              "id": 20,
              "canEdit": null,
              "canRead": null,
              "isAuthor": null,
              "isHidden": null,
              "inactive": null,
              "createdAt": "2016-11-20T21:32:16.056Z",
              "updatedAt": "2016-11-20T21:32:16.056Z",
              "userId": 2,
              "pubId": 9,
              "roles": [],
              "user": {
                  "id": 2,
                  "username": "marco",
                  "firstName": "Marco",
                  "lastName": "Delinreq",
                  "avatar": "https://avatar.com/example.jpg"
              }
            }
    500:
      body:
        application/json:
          example: |
            {
              error : "Error creating new contributor"
            }
put:
  description: |
    Used to allow a pub editor to update the contributor 
  body:
    application/json:
      formParameters:
        pubId: 
          description: pub which owns the given contributor to be edited
          required: true
        contributorId: 
          description: id of the contributor to be updated
          required: true
        canEdit: 
          description: whether this contributor can edit this pub
        canRead: 
          description: whether this contributor can read private content in this pub
        isAuthor:
          description: whether this contributor is listed as an author
        isHidden:
          description: whether this contributor is hidden from public display
  responses:
    200:
      body:
        application/json:
          example: true
    500:
      body:
        application/json:
          example: |
            {
              error : "Error updating contributor"
            }
delete:
  description: Delete the pub
  body:
    application/json:
      formParameters:
        pubId: 
          description: pub which owns the given contributor to be removed
          required: true
        contributorId: 
          description: id of the contributor to be removed
          required: true
  responses:
    200:
      body:
        application/json:
          example: "Pub set inactive"
    500:
      body:
        application/json:
          example: |
            {
              error : "Error deleting pub"
            }

/role: !include ../pubContributorRole/pubContributorRole.raml            