displayName: Version
description: Routes to access data about a pub's versions
post:
  description: Create a new version. New files are added through this interface
  body:
    application/json:
      formParameters:
        pubId: 
          description: id of the Pub this version will be attached to
          required: true
          type: number
        message: 
          description: message for this given version
          required: true
        isPublished:
          description: Boolean for whether this version should be published
          required: true
        files: 
          description: All files, those that are new should NOT include an "id" field and they will be added.
        defaultFile:
          description: Default file for this version
        newFileAttribution: 
          description: |
            Array of objects with {source: [file.name], destination: [file.name]}. 
        newFileRelations: 
          description: |
            Array of objects with {fileName: [file.name], userId: [user's id]}. 

  responses:
    200:
      body:
        application/json:
          example: |
            {
                "id": 15,
            }
    500:
      body:
        application/json:
          example: |
            {
              error : "Error creating pub"
            }
put:
  description: |
    Set values associated with the version.
  body:
    application/json:
      formParameters:
        pubId: 
          description: id of the pub to be changed
          required: true
          type: number
        versionId: 
          description: id of the version to be changed
          required: true
          type: number
        doi: 
          description: new DOI for a given version
        defaultFile: 
          description: new defautlFile for a given version
  responses:
    200:
      body:
        application/json:
          example: true
    500:
      body:
        application/json:
          example: |
            {
              error : "Error updating pub"
            }

/doi: !include ../pubVersionDoi/pubVersionDoi.raml