displayName: Pub
description: Routes to access data about a Pub's followers
get: 
  description: Get a list of all followers
  queryParameters:
    pubId:
      type: number
      required: true
  responses:
    200:
      body:
        application/json:
          example: |
            [
              {
                  "id": 1,
                  "username": "jane-doe",
                  "firstName": "Jane",
                  "lastName": "Doe",
                  "image": "http://images.com/example.jpg"
              }
            ]
    500:
      body:
        application/json:
          example: "Pub not found"
post:
  description: Create a new Follow
  body:
    application/json:
      formParameters:
        pubId: 
          description: id of the pub that will be followed.
          required: true
          type: number
  responses:
    200:
      body:
        application/json:
          example: |
            {
              "followerId": 1,
              "pubId": 3,
              "updatedAt": "2016-11-22T02:10:21.874Z",
              "createdAt": "2016-11-22T02:10:21.874Z"
            }
    500:
      body:
        application/json:
          example: |
            {
              error : "Error following pub"
            }
delete:
  description: Remove a follow
  body:
    application/json:
      formParameters:
        pubId: 
          description: id of the pub to remove follow from
          required: true
          type: number
  responses:
    200:
      body:
        application/json:
          example: "true"
    500:
      body:
        application/json:
          example: |
            {
              error : "Error deleting follow"
            }