displayName: Logout
description: Used to logout the user associated with cookies
get:
  description: Logout the given user based on their cookie
  responses:
    200:
      body:
        application/json:
          example: true