displayName: Labels
description: Routes to access data about a the labels associated with a pub
get: 
  description: Get pub data. Includes connected user, discussion, label, etc data. If the user's cookie or token is included, private data (private discussions, versions, etc) are included.
  queryParameters:
    pubId:
      type: string
      required: true
  responses:
    200:
      body:
        application/json:
          example: |
            {
                id: 9,
            }
    500:
      body:
        application/json:
          example: "Pub not found"
post:
  description: Create a PubLabel. The relation between a pub and a label
  body:
    application/json:
      formParameters:
        pubId: 
          description: id of the pub the label is being applied to
          required: true
        labelId: 
          description: id of the label to be applied
          required: true
  responses:
    200:
      body:
        application/json:
          example: |
            {
                "id": 15,
            }
    500:
      body:
        application/json:
          example: |
            {
              error : "Error creating pub"
            }
delete:
  description: Delete the label relationship
  body:
    application/json:
      formParameters:
        pubId: 
          description: id of the pub the label is being applied to
          required: true
        labelId: 
          description: id of the label to be applied
          required: true
  responses:
    200:
      body:
        application/json:
          example: "Pub set inactive"
    500:
      body:
        application/json:
          example: |
            {
              error : "Error deleting pub"
            }