#%RAML 0.8
title: PubPub
version: v1.0
protocols: [ HTTP ]
baseUri: http://localhost:9876
mediaType: application/json
/users:
  /{id}:
    put:
    post:
    delete:
    get:
      queryParameters:
        name:
          type: string
  /new:
    post:
      queryParameters:
        name:
          type: string
        id:
          type: integer
/lists:
  get:
  put:
  post:
  delete:
