#%RAML 0.8
title: PubPub
documentation:
  - title: Welcome
    content: |
      hi
version: v1.0
protocols: [ HTTP ]
baseUri: http://localhost:9876
mediaType: application/json
/users:
  get:
  /{id}:
    put:
    post:
    delete:
    get:
      description: |
        get the user you deserve
      queryParameters:
        name:
          type: string
  /new:
    post:
      queryParameters:
        name:
          type: string
        id:
          type: integer
/lists:
  get:
  put:
  post:
  delete:
