#%RAML 0.8
title: PubPub
documentation:
  - title: Introduction
    content: |
      This is the introduction PubPub API
version: v1.0
protocols: [ HTTP ]
baseUri: http://localhost:9876
mediaType: application/json
/users:
  description: |
    get all the users bro
  get:
    description: |
      no rly
  /{id}:
    put:
    post:
    delete:
    get:
      description: |
        get the user you deserve
      queryParameters:
        name:
          type: string
  /new:
    post:
      queryParameters:
        name:
          type: string
        id:
          type: integer
/journals:
  description: |
    Journals API description
  /{slug}:
    get:
      # should return journal details
    /featured:
      get:
    /articles:
      get:
    /collections:
      get:
    /collection:
      /{id}:
        get:
