displayName: Follows Label
description: Routes to access data about a Label's followers
get: 
  description: Get a list of all followers
  queryParameters:
    labelId:
      type: string
      required: true
  responses:
    200:
      body:
        application/json:
          example: |
            [
              {
                  "id": 1,
                  "username": "jane-doe",
                  "firstName": "Jane",
                  "lastName": "Doe",
                  "image": "http://images.com/example.jpg"
              }
            ]
    500:
      body:
        application/json:
          example: "Label not found"
post:
  description: Create a new Follow
  body:
    application/json:
      formParameters:
        labelId: 
          description: id of the label that will be followed.
          required: true
  responses:
    200:
      body:
        application/json:
          example: |
            {
              "followerId": 1,
              "labelId": 3,
              "updatedAt": "2016-11-22T02:10:21.874Z",
              "createdAt": "2016-11-22T02:10:21.874Z",
              "notifyOnNewVersion": null,
              "notifyOnNewFeature": null,
              "notifyOnNewDiscussions": null
            }
    500:
      body:
        application/json:
          example: |
            {
              error : "Error following label"
            }
put:
  description: edit the values of the follow
  body:
    application/json:
      formParameters:
        labelId: 
          description: id of the label that will have follow data updated.
          required: true
        notifyOnNewVersion:
          description: whether notifications are created for new versions. 
  responses:
    200:
      body:
        application/json:
          example: "true"
    500:
      body:
        application/json:
          example: |
            {
              error : "Error updated Follow"
            }            
delete:
  description: Remove a follow
  body:
    application/json:
      formParameters:
        labelId: 
          description: id of the label to remove follow from
          required: true
  responses:
    200:
      body:
        application/json:
          example: "true"
    500:
      body:
        application/json:
          example: |
            {
              error : "Error deleting follow"
            }