displayName: Reset Password Request
description: Used to reset a users password
post:
  description: Request to reset a users password.
  body:
    application/json:
      formParameters:
        email:
          description: email of the account to login
          required: true
  responses:
    200:
      body:
        application/json:
          example: |
            {
            }
    401:
      body:
        application/json:
          example: "Unauthorized"
