displayName: Reset
description: Used to reset a users password
get:
  description: Check a reset hash.
  queryParameters:
    resetHash:
      type: string
      required: true
    username:
      type: string
      required: true
  responses:
    200:
      body:
        application/json:
          example: true
    401:
      body:
        application/json:
          example: "Hash is invalid"
post:
  description: Request to reset a users password.
  body:
    application/json:
      formParameters:
        email:
          description: email of the account to login
          required: true
  responses:
    200:
      body:
        application/json:
          example: |
            {
            }
    401:
      body:
        application/json:
          example: "Unauthorized"