displayName: User
description: Routes to access data about a User's followers
get: 
  description: Get a list of all followers
  queryParameters:
    userId:
      type: string
      required: true
  responses:
    200:
      body:
        application/json:
          example: |
            [
              {
                  "id": 1,
                  "username": "jane-doe",
                  "firstName": "Jane",
                  "lastName": "Doe",
                  "image": "http://images.com/example.jpg"
              }
            ]
    500:
      body:
        application/json:
          example: "User not found"
post:
  description: Create a new Follow
  body:
    application/json:
      formParameters:
        userId: 
          description: id of the user that will be followed.
          required: true
  responses:
    200:
      body:
        application/json:
          example: |
            {
              "followerId": 1,
              "userId": 3,
              "updatedAt": "2016-11-22T02:10:21.874Z",
              "createdAt": "2016-11-22T02:10:21.874Z"
            }
    500:
      body:
        application/json:
          example: |
            {
              error : "Error following user"
            }        
delete:
  description: Remove a follow
  body:
    application/json:
      formParameters:
        userId: 
          description: id of the user to remove follow from
          required: true
  responses:
    200:
      body:
        application/json:
          example: "true"
    500:
      body:
        application/json:
          example: |
            {
              error : "Error deleting follow"
            }